import PDFDocument from 'pdfkit'
import crypto from 'crypto'

interface AgreementData {
  id: string
  propertyTitle: string
  propertyAddress: string
  landlordName: string
  tenantName: string
  startDate: string
  endDate: string
  rentAmount: number
  rentPeriod: string
  cautionDeposit?: number
  specialClauses?: string
}

interface SignatureData {
  verifiedName: string
  verifiedDob: string
  idType: string
  idNumberMasked: string
  signedAt: Date
  ipAddress: string
}

const STANDARD_CLAUSES = [
  'The Tenant shall pay rent on or before the due date each period. Late payments may attract penalties as specified by the Landlord.',
  'The Tenant shall maintain the property in good condition and shall be responsible for minor repairs not exceeding ₦20,000.',
  'The Tenant shall not sublet or assign the property without the written consent of the Landlord.',
  'The caution deposit shall be refunded within 30 days of the end of tenancy, less any deductions for damages or unpaid rent.',
  'Either party may terminate this agreement by giving the notice period specified, in writing.',
  'The Landlord reserves the right to inspect the property with 24 hours prior notice during reasonable hours.',
  'This agreement shall be governed by the laws of the Federal Republic of Nigeria.',
]

function collectPdfBuffer(doc: InstanceType<typeof PDFDocument>): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
  })
}

export async function generateAgreementPDF(data: AgreementData): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 })
  const bufferPromise = collectPdfBuffer(doc)

  // Header
  doc.fontSize(10).fillColor('#c9952a').text('PROPATI', { align: 'center' })
  doc.fontSize(8).fillColor('#666666').text("Nigeria's Verified Property Platform", { align: 'center' })
  doc.moveDown(1.5)

  // Title
  doc.fontSize(18).fillColor('#000000').text('TENANCY AGREEMENT', { align: 'center' })
  doc.moveDown(0.5)
  doc.fontSize(9).fillColor('#666666').text(`Agreement ID: ${data.id}`, { align: 'center' })
  doc.moveDown(1.5)

  // Parties
  doc.fontSize(12).fillColor('#000000').text('PARTIES', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  doc.text(`Landlord: ${data.landlordName}`, { continued: false })
  doc.text(`Tenant: ${data.tenantName}`)
  doc.moveDown(1)

  // Property details
  doc.fontSize(12).text('PROPERTY DETAILS', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  doc.text(`Property: ${data.propertyTitle}`)
  doc.text(`Address: ${data.propertyAddress}`)
  doc.text(`Tenancy Period: ${data.startDate} to ${data.endDate}`)
  doc.text(`Rent: ₦${data.rentAmount.toLocaleString('en-NG')} per ${data.rentPeriod}`)
  if (data.cautionDeposit) {
    doc.text(`Caution Deposit: ₦${data.cautionDeposit.toLocaleString('en-NG')}`)
  }
  doc.moveDown(1)

  // Standard clauses
  doc.fontSize(12).text('TERMS AND CONDITIONS', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  STANDARD_CLAUSES.forEach((clause, i) => {
    doc.text(`${i + 1}. ${clause}`, { indent: 10 })
    doc.moveDown(0.3)
  })
  doc.moveDown(0.5)

  // Special clauses
  if (data.specialClauses) {
    doc.fontSize(12).text('SPECIAL CLAUSES', { underline: true })
    doc.moveDown(0.5)
    doc.fontSize(10).text(data.specialClauses)
    doc.moveDown(1)
  }

  // Signature blocks
  doc.fontSize(12).text('SIGNATURES', { underline: true })
  doc.moveDown(1)

  doc.fontSize(10).text('Landlord Signature:')
  doc.moveDown(0.5)
  doc.text('_____________________________')
  doc.text(`Name: ${data.landlordName}`)
  doc.text('Date: ____________________')
  doc.moveDown(1)

  doc.text('Tenant Signature:')
  doc.moveDown(0.5)
  doc.text('_____________________________')
  doc.text(`Name: ${data.tenantName}`)
  doc.text('Date: ____________________')
  doc.moveDown(1.5)

  // Legal footer
  doc.fontSize(7).fillColor('#999999')
  doc.text(
    'This document is generated by PROPATI and is legally binding when signed electronically in accordance with the Nigeria Cybercrimes (Prohibition, Prevention, Etc.) Act 2015 and the Evidence Act 2011.',
    { align: 'center' }
  )

  doc.end()
  return bufferPromise
}

export async function generateSignedPDF(
  data: AgreementData,
  signatures: { landlord?: SignatureData; tenant?: SignatureData },
  documentHash: string
): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'A4', margin: 50 })
  const bufferPromise = collectPdfBuffer(doc)

  // Header
  doc.fontSize(10).fillColor('#c9952a').text('PROPATI', { align: 'center' })
  doc.fontSize(8).fillColor('#666666').text("Nigeria's Verified Property Platform", { align: 'center' })
  doc.moveDown(1.5)

  // Title
  doc.fontSize(18).fillColor('#000000').text('TENANCY AGREEMENT', { align: 'center' })
  doc.fontSize(10).fillColor('#0e7c6a').text('FULLY SIGNED', { align: 'center' })
  doc.moveDown(0.5)
  doc.fontSize(9).fillColor('#666666').text(`Agreement ID: ${data.id}`, { align: 'center' })
  doc.moveDown(1.5)

  // Parties
  doc.fontSize(12).fillColor('#000000').text('PARTIES', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  doc.text(`Landlord: ${data.landlordName}`)
  doc.text(`Tenant: ${data.tenantName}`)
  doc.moveDown(1)

  // Property details
  doc.fontSize(12).text('PROPERTY DETAILS', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  doc.text(`Property: ${data.propertyTitle}`)
  doc.text(`Address: ${data.propertyAddress}`)
  doc.text(`Tenancy Period: ${data.startDate} to ${data.endDate}`)
  doc.text(`Rent: ₦${data.rentAmount.toLocaleString('en-NG')} per ${data.rentPeriod}`)
  if (data.cautionDeposit) {
    doc.text(`Caution Deposit: ₦${data.cautionDeposit.toLocaleString('en-NG')}`)
  }
  doc.moveDown(1)

  // Standard clauses
  doc.fontSize(12).text('TERMS AND CONDITIONS', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(10)
  STANDARD_CLAUSES.forEach((clause, i) => {
    doc.text(`${i + 1}. ${clause}`, { indent: 10 })
    doc.moveDown(0.3)
  })

  if (data.specialClauses) {
    doc.moveDown(0.5)
    doc.fontSize(12).text('SPECIAL CLAUSES', { underline: true })
    doc.moveDown(0.5)
    doc.fontSize(10).text(data.specialClauses)
  }

  // Signature certificate page
  doc.addPage()
  doc.fontSize(16).fillColor('#000000').text('ELECTRONIC SIGNATURE CERTIFICATE', { align: 'center' })
  doc.moveDown(0.5)
  doc.fontSize(9).fillColor('#666666').text(`Agreement ID: ${data.id}`, { align: 'center' })
  doc.moveDown(1.5)

  function renderSignatureBlock(label: string, sig?: SignatureData) {
    doc.fontSize(12).fillColor('#000000').text(label, { underline: true })
    doc.moveDown(0.5)
    if (sig) {
      doc.fontSize(10)
      doc.text(`Verified Name: ${sig.verifiedName}`)
      doc.text(`ID Type: ${sig.idType.replace('_', ' ').toUpperCase()}`)
      doc.text(`ID Number: ${sig.idNumberMasked}`)
      doc.text(`Date of Birth: ${sig.verifiedDob}`)
      doc.text(`Signed At: ${sig.signedAt.toISOString()}`)
      doc.text(`IP Address: ${sig.ipAddress}`)
      doc.fillColor('#0e7c6a').text('✓ Identity verified via Dojah', { align: 'left' })
      doc.fillColor('#000000')
    } else {
      doc.fontSize(10).text('Not yet signed')
    }
    doc.moveDown(1)
  }

  renderSignatureBlock('LANDLORD SIGNATURE', signatures.landlord)
  renderSignatureBlock('TENANT SIGNATURE', signatures.tenant)

  // Document integrity
  doc.moveDown(1)
  doc.fontSize(12).text('DOCUMENT INTEGRITY', { underline: true })
  doc.moveDown(0.5)
  doc.fontSize(9).fillColor('#666666')
  doc.text(`Document Hash (SHA-256): ${documentHash}`)
  doc.text(`Generated: ${new Date().toISOString()}`)
  doc.moveDown(1.5)

  doc.fontSize(7).fillColor('#999999')
  doc.text(
    'This electronically signed document is legally binding under the Nigeria Cybercrimes (Prohibition, Prevention, Etc.) Act 2015 and the Evidence Act 2011. All signatories have been identity-verified via government-issued ID through Dojah.',
    { align: 'center' }
  )

  doc.end()
  return bufferPromise
}

export function hashDocument(buffer: Buffer): string {
  return crypto.createHash('sha256').update(buffer).digest('hex')
}
